// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using netcore_spatial.Data;

namespace netcore_spatial.Migrations
{
    [DbContext(typeof(SpatialDbContext))]
    [Migration("20200606100701_SeedMoreData")]
    partial class SeedMoreData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("netcore_spatial.Data.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnName("point")
                        .HasColumnType("geography (point)");

                    b.HasKey("Id");

                    b.ToTable("place");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56cef075-da90-4977-b808-a22a26da9d1c"),
                            Name = "Monumen Nasional",
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.8232042 -6.1778625)")
                        },
                        new
                        {
                            Id = new Guid("0e7b76df-7aba-4ed0-88c9-abe602b319ca"),
                            Name = "Tanah Abang",
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.7899549 -6.2054172)")
                        },
                        new
                        {
                            Id = new Guid("dea028cc-b7b8-4ada-8667-f1f572e51bc4"),
                            Name = "Soekarno-Hatta International Airport",
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.6515171 -6.1275282)")
                        },
                        new
                        {
                            Id = new Guid("2472e920-c88f-4ab6-9ac9-7b0b6dca5429"),
                            Name = "Halim Perdanakusuma Airport",
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.88239 -6.2653365)")
                        },
                        new
                        {
                            Id = new Guid("4fab1364-e3c3-4602-992a-25aca3f2351d"),
                            Name = "Trans Studio Bandung",
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (107.6001837 -6.9072212)")
                        },
                        new
                        {
                            Id = new Guid("3b3bddfa-70cc-4382-9234-9c1400dc5e69"),
                            Name = "Gedung Sate",
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (107.6230286 -6.8928316)")
                        },
                        new
                        {
                            Id = new Guid("222c7934-e201-45e2-bd92-ba891ec74e5e"),
                            Name = "Surabaya Town Square",
                            Point = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (112.7280482 -7.2946663)")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
